# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bf252fb35c6e46eb9da70a4ccfc6e8c21c0a2a79c28c8e66b52ea2bc6800e3b6f09e0882e38e2999213b3c76db4b8445c653dc107d26dbae6c447367dfd2b0a

test:
  secret_key_base: 440761b123dfa6daacef05e26ee78c3203e2c7cb5a676ee2c8d9f991fa6e03f441fc21ec6f11138424fb31b630da7bc7efc8e95642ec6598fa00d1b85066b623

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
